[package]

name = "lockfree"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-lockfree.git"
description = "Lock free concurrent data structures"
readme = "README.md"
license = "MIT"

